# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script:
    - apt update && apt -y install cmake
  script:
    - cmake -S . -B build
    - cmake --build build
  artifacts:
    paths:
      - build


# run tests using the binary built before
test:
  stage: test
  script:
    - build/bin/tsne_test --gtest_output="xml:report.xml"
  artifacts:
      when: always
      reports:
        junit: report.xml